Add documentation, organize requests files, add collection requests and data utils
moduloTech/kaze_client pull request #7
Opened 2023-02-18 01:22 UTC by Richar-p

- Init YARD to create documentation
- Organize requests files
- Add collections requests
- Add DataUtils module
- Fix Specs
- Fix CI

2023-02-20 06:57 UTC, Ezveus requested changes

2023-02-20 06:57 UTC, Ezveus commented on lib/kaze_client/data_utils.rb
> +    #  KazeClient::KazeWorkflowUtils.parse_datetime(1546300800000)
```suggestion
    #  KazeClient::DataUtils.parse_datetime(1546300800000)
```

2023-02-20 06:57 UTC, Ezveus commented on lib/kaze_client/data_utils.rb
> +      Time.at(time.to_i / 1000).utc
You should handle when time is `nil` and probably when `time` is a `String` too.

2023-02-20 06:57 UTC, Ezveus commented on lib/kaze_client/request/request.rb
> +      when 401 then KazeClient::Error::Unauthorized.new(message)
Why this change?

2023-02-20 06:57 UTC, Ezveus commented on lib/kaze_client/request/requests/collections/items/items_request.rb
> +    def initialize(id)
```suggestion

    def initialize(id)
```

2023-02-20 06:57 UTC, Ezveus commented on lib/kaze_client/request/requests/jobs/add_tag_request.rb
> +  # @note    This request is for the moment in re-development. It's not working well
```suggestion
  # @note    This request is for the moment in re-development. It is not working well.
```

2023-02-20 06:57 UTC, Ezveus commented on lib/kaze_client/request/requests/jobs/add_tag_request.rb
> +  #          When you add a tag with it, it doesnt check if the id is correct or not and it delete all the other tags
```suggestion
  #          When you add a tag with it, it does not check if the id is correct or not and it deletes all the other tags.
```

2023-02-20 06:57 UTC, Ezveus commented on lib/kaze_client/request/requests/jobs/add_tag_request.rb
> +  #          It will be fixed in the next version of Kaze API, but for now, we use it like that
```suggestion
  #          It should be fixed in a next version of Kaze API.
```

2023-02-20 06:57 UTC, Ezveus commented on lib/kaze_client/request/requests/jobs/add_tag_request.rb
> +      super(:put, "/api/tags/references/job/#{job_id}.json")
```suggestion
      super(:put, "/api/tags/references/job/#{job_id}")

```

2023-02-20 06:57 UTC, Ezveus commented on lib/kaze_client/request/requests/jobs/add_tag_request.rb
> +  #       "Authorization": "token"
```suggestion
  #       "Authorization": "token", "Content-Type": "application/json", "Accept": "application/json"
```

2023-02-20 06:57 UTC, Ezveus commented on lib/kaze_client/request/requests/jobs/add_tag_request.rb
> +  #    PUT https://kaze.modulotech.fr/api/tags/references/job/123.json
```suggestion
  #    PUT https://kaze.modulotech.fr/api/tags/references/job/123
```

2023-02-20 17:18 UTC, Richar-p commented on lib/kaze_client/data_utils.rb
> +      Time.at(time.to_i / 1000).utc
Agree for the nil

But for the string, i use .to_i to handle it.

2023-02-20 17:18 UTC, Richar-p commented on lib/kaze_client/request/request.rb
> +      when 401 then KazeClient::Error::Unauthorized.new(message)
To be rubocop compliant

2023-04-17 09:23 UTC, Richar-p commented
Up! :)

2023-04-23 08:58 UTC, Ezveus commented
Manually merged.

2023-04-23 08:58 UTC, closed without merging